package br.com.ecad.sgaapi.model;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

/**
 * TituloCobranca generated by hbm2java
 */
@Entity
@Table(name = "TITULO_COBRANCA")
public class TituloCobranca implements java.io.Serializable {

	private static final long serialVersionUID = 8618800586847186488L;
	
	private long idTituloCobranca;
	private String usuario;
	private Date dtCompetencia;
	private BigDecimal vlrCobranca;
	private short qtdParcelas;
	private String indCancelado;
	private String usuarioSistema;
	private String txtJustificativaCancel;
	private Date datCancelamento;
	private short nivel;
	private String creditoTituloCobrancas;
	private String parcelas;

	public TituloCobranca() {
	}

	public TituloCobranca(long idTituloCobranca, String usuario, Date datCompetencia, BigDecimal vlrCobranca,
			short qtdParcelas, String indCancelado, String usuarioSistema, String txtJustificativaCancel, 
			Date datCancelamento, short nivel) {
		this.idTituloCobranca = idTituloCobranca;
		this.usuario = usuario;
		this.dtCompetencia = datCompetencia;
		this.vlrCobranca = vlrCobranca;
		this.qtdParcelas = qtdParcelas;
		this.indCancelado = indCancelado;
		this.usuarioSistema = usuarioSistema;
		this.txtJustificativaCancel = txtJustificativaCancel;
		this.datCancelamento = datCancelamento;
		this.nivel = nivel;
	}

	public TituloCobranca(long idTituloCobranca, String usuario, Date datCompetencia, BigDecimal vlrCobranca,
			short qtdParcelas,
			String creditoTituloCobrancas,
			String parcelas, String indCancelado, String usuarioSistema, String txtJustificativaCancel,
			Date datCancelamento, short nivel) {
		this.idTituloCobranca = idTituloCobranca;
//	this.carteira = carteira;
		this.usuario = usuario;
		this.dtCompetencia = datCompetencia;
		this.vlrCobranca = vlrCobranca;
		this.qtdParcelas = qtdParcelas;
		this.creditoTituloCobrancas = creditoTituloCobrancas;
		this.parcelas = parcelas;
		this.indCancelado = indCancelado;
		this.usuarioSistema = usuarioSistema;
		this.txtJustificativaCancel = txtJustificativaCancel;
		this.datCancelamento = datCancelamento;
		this.nivel = nivel;
	}

	@Id
	@Column(name = "COD_TITULO_COBRANCA", unique = true, nullable = false, precision = 9, scale = 0)
	public long getIdTituloCobranca() {
		return this.idTituloCobranca;
	}

	public void setIdTituloCobranca(long idTituloCobranca) {
		this.idTituloCobranca = idTituloCobranca;
	}
	
	@NotNull
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}
	
	@NotNull
	public String getUsuarioSistema() {
		return usuarioSistema;
	}

	public void setUsuarioSistema(String usuarioSistema) {
		this.usuarioSistema = usuarioSistema;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DAT_COMPETENCIA", nullable = false, length = 7)
	@NotNull
	public Date getDtCompetencia() {
		return this.dtCompetencia;
	}

	public void setDtCompetencia(Date dtCompetencia) {
		this.dtCompetencia = dtCompetencia;
	}

	@Column(name = "VLR_COBRANCA", nullable = false, precision = 11)
	@NotNull
	public BigDecimal getVlrCobranca() {
		return this.vlrCobranca;
	}

	public void setVlrCobranca(BigDecimal vlrCobranca) {
		this.vlrCobranca = vlrCobranca;
	}

	
	@Column(name = "IND_CANCELADO", nullable = false, length = 1)
	@NotNull
	public String getIndCancelado() {
		return this.indCancelado;
	}

	public void setIndCancelado(String indCancelado) {
		this.indCancelado = indCancelado;
	}

	@Column(name = "QTD_PARCELAS", nullable = false, precision = 2, scale = 0)
	public short getQtdParcelas() {
		return this.qtdParcelas;
	}

	public void setQtdParcelas(short qtdParcelas) {
		this.qtdParcelas = qtdParcelas;
	}
	
	public String getCreditoTituloCobrancas() {
		return this.creditoTituloCobrancas;
	}

	public void setCreditoTituloCobrancas(
			String creditoTituloCobrancas) {
		this.creditoTituloCobrancas = creditoTituloCobrancas;
	}
	
	public String getParcelas() {
		return this.parcelas;
	}

	public void setParcelas(String parcelas) {
		this.parcelas = parcelas;
	}
	
	@Column(name = "TXT_JUSTIFICATIVA_CANCEL", nullable = true)
	public String getTxtJustificativaCancel() {
		return this.txtJustificativaCancel;
	}

	public void setTxtJustificativaCancel(String txtJustificativaCancel) {
		this.txtJustificativaCancel = txtJustificativaCancel;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DAT_CANCELAMENTO", nullable = true, length = 7)
	public Date getDtCancelamento() {
		return this.datCancelamento;
	}

	public void setDtCancelamento(Date dtCancelamento) {
		this.datCancelamento = dtCancelamento;
	}
	
	@Column(name = "NRO_NIVEL", nullable = false, precision = 3, scale = 0)
	public short getNivel() {
		return this.nivel;
	}
	
	public void setNivel(short nivel) {
		this.nivel = nivel;
	}
}